baseURL = "https://shotasaitov.github.io/circle_webpage/"
languageCode = "ja"
title = "電脳猫太朗"
theme = "hugo.386"
paginate = 10  # 1ページに表示する記事数

[params]
    # ホームページのメインタイトルとして表示する名前
    mainpagetitle = "DennoNekotaro"

    # ホームページのタイトルの下に表示するサブタイトル
    mainpagesubtitle = "サークルのページへようこそ！"

    # ウェブサイトの説明。ホームページに表示されます
    mainpagedesc = "同人サークル　電脳猫太朗（でんのうねこたろう）のWebサイトです"

    # フッターの著作権セクションに表示する名前
    # copyrightname = "JM Fergeau"

    # 著作権名にリンクさせるURL。空欄にするとリンクなしになります。
    # copyrighturl = "http://jmf-portfolio.netlify.com"

    # 「built on Hugo」の表示を表示します
    showhugo = true

    # ローディングアニメーションを有効・無効にします。falseで有効化されます。既定値はfalseです。
    loadfastload = false

    # ページ読み込み効果の速度を設定します。既定値は1.0です。
    loadspeedfactor = 1.0

    # 2つ目の飛行カーソルを有効にします。既定値はfalseです。
    loadonepass = false

[params.copyright]
    # name = "JM Fergeau"

    # 著作権名にリンクさせるURL。空欄にするとリンクなしになります。
    # url = "http://jmf-portfolio.netlify.com"

    # 著作権情報の前に表示するテキスト
    prefix = "[hugo.386テーマ by Max le Fou](https://gitlab.com/maxlefou/hugo.386)"

    # 著作権情報と Hugo の免責事項の間に表示するテキスト
    suffix = "電脳猫太朗"

[menu]
  # ナビゲーションバーに表示するボタンからコンテンツへアクセスできるようにします
  [[menu.main]]
    identifier = "about" # ボタンの一意の識別子
    name = "about"       # ナビゲーションバーに表示する表示名
    url = "/about/"      # パスは単一ページだけでなく、コンテンツフォルダにもなります
    weight = 10          # ナビゲーションバーのボタンの並び順を決める番号

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/post/"       # パスはコンテンツフォルダにもなります
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"